# Generated by Django 2.1.7 on 2019-03-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190329_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
